# docker-compose.yml

version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: today
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django