version: "3"

services:
  django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=crud
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=crud
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
